-- Store a concise, source-backed company introduction generated by the AI research action.
alter table public.prospects
  add column if not exists ai_company_summary text,
  add column if not exists ai_company_sources jsonb not null default '[]'::jsonb,
  add column if not exists ai_company_analyzed_at timestamptz;
